name: Qt 6.9.0 | macos
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out Qt 
        uses: actions/checkout@v4
        with: 
          repository: 'qt/qt5'
          ref: 'v6.9.0'
          fetch-depth: 1
      - name: Create install dir
        run: mkdir qt_install_dir
      - name: Configure Qt, build and install Qt
        run: ./configure -init-submodules -prefix ./qt_install_dir -release -submodules qtbase,qttools,qtsvg,qtimageformats -- -DCMAKE_OSX_ARCHITECTURES="arm64"
      - name: Build Qt
        run: cmake --build . --parallel
      - name: Install Qt
        run: cmake --install .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'qt-6.9.0-macos'
          path: ./qt_install_dir/
          