name: Qt 6.9.0 | win64
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out Qt 
        uses: actions/checkout@v4
        with: 
          repository: 'qt/qt5'
          ref: 'v6.9.0'
          fetch-depth: 1
      - name: Create install dir
        run: mkdir qt_install_dir
      - name: Configure submodules
        run: configure.bat -init-submodules -force-debug-info -prefix ./qt_install_dir -release -submodules qtbase,qttools,qtsvg,qtimageformats
      - name: Build Qt
        run: cmake --build . --parallel
      - name: Install Qt
        run: cmake --install .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'qt-6.9.0-win64'
          path: ./qt_install_dir/